services:
  - type: web
    name: photo-enhancer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run photo_enhancer.py --server.port=10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
