services:
  - type: web
    name: photo-enhancer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run photo_enhancer.py
    envVars:
      - key: PORT
        value: 8501
    plan: free
